---
# ingestion service port
ingestionServicePort: 9091

# ZK ensemble - the list of zk Servers
zkEnsemble:
  - 'localhost:2181'
  - 'localhost:2182'

# storage directories and the upper limits on the usage used for storing data (in GB)
storageDirs:
  /sustain/data/a : 10
  /sustain/data/b : 10

# how the storage directories are chosen from available options listed under 'storageDirs'
storageAllocationPolicy: 'round-robin'

# location of the root commit log
rootJournalLoc: '/tmp/$HOSTNAME-root-journal.slog'

# upper limit on the memory utilization by a memTable (in MB)
memTableSize: 50

# block size used when creating on-disk ssTables (in MB)
blockSize: 10

# metadata storage directory - used for storing metadata of entity stores (e.g.: commit logs)
metadataStoreDir: '/tmp/'

# writer pool size
writerPoolSize: 10

metadataServicePort: 9092
metadataHost: 'lattice-7'
metadataJournalLoc: '/s/parsons/b/others/sustain/sustain/metadata-journal.mlog'

...
